// ============================================================
// townfolk.ts — The 20 unique organism definitions of Veridion Hollow
// ============================================================
import { OrganismDefinition } from './organism';

export const TOWNFOLK_DEFINITIONS: OrganismDefinition[] = [
  {
    name: 'Maren Ashveil',
    backstory: 'Former cartographer who mapped impossible places. Arrived in Veridion Hollow chasing a map that drew itself.',
    pros: ['Exceptional spatial awareness', 'Natural leader'],
    cons: ['Obsessive', "Can't let go of mysteries"],
    superpowerNames: ['Chrono Glimpse', 'Shadow Step'],
    initialTraits: { courage: 0.75, curiosity: 0.85, wisdom: 0.7, charisma: 0.65 },
    initialEmotion: 'determined',
  },
  {
    name: 'Dorian Kael',
    backstory: "Blacksmith's son who discovered he could shape emotions like metal. Quiet, watchful.",
    pros: ['Deeply empathetic', 'Steady hands'],
    cons: ["Absorbs others' pain", 'Prone to melancholy'],
    superpowerNames: ['Verdant Touch', 'Mind Link'],
    initialTraits: { empathy: 0.9, resilience: 0.65, aggression: 0.2, wisdom: 0.7 },
    initialEmotion: 'melancholy',
  },
  {
    name: 'Sable Voss',
    backstory: 'Rogue scholar expelled for "dangerous curiosity." Knows things nobody should.',
    pros: ['Brilliant intellect', 'Fearless'],
    cons: ['Arrogant', 'Trusts no one'],
    superpowerNames: ['Echo Memory', 'Pulse Sight'],
    initialTraits: { curiosity: 0.95, cunning: 0.85, empathy: 0.25, wisdom: 0.8 },
    initialEmotion: 'excited',
  },
  {
    name: 'Theta-7',
    backstory: 'An anomaly — not born but assembled from fragments of failed experiments. Seeks purpose.',
    pros: ['Adaptable', 'Immune to fear'],
    cons: ['No childhood memories', 'Identity crisis'],
    superpowerNames: ['Iron Will', 'Null Field'],
    initialTraits: { resilience: 0.9, courage: 0.85, empathy: 0.3, curiosity: 0.75 },
    initialEmotion: 'calm',
  },
  {
    name: 'Lira Sunhollow',
    backstory: 'Traveling musician whose songs literally change the weather. Warm-hearted wanderer.',
    pros: ['Infectious joy', 'Creative genius'],
    cons: ['Flighty', 'Avoids commitment'],
    superpowerNames: ['Ember Voice', 'Rift Walk'],
    initialTraits: { charisma: 0.9, creativity: 0.9, discipline: 0.3, empathy: 0.75 },
    initialEmotion: 'joyful',
  },
  {
    name: 'Crag Dunmore',
    backstory: 'Ex-soldier who broke his oath to protect the innocent. Haunted by guilt.',
    pros: ['Unbreakable discipline', 'Combat instinct'],
    cons: ['PTSD', 'Slow to trust'],
    superpowerNames: ['Titan Skin', 'Iron Will'],
    initialTraits: { discipline: 0.9, courage: 0.8, empathy: 0.35, resilience: 0.85 },
    initialEmotion: 'anxious',
  },
  {
    name: 'Wren Lostlight',
    backstory: 'Orphan raised by the forest. Speaks to animals, fears crowds.',
    pros: ['Deep nature connection', 'Survival expert'],
    cons: ['Social anxiety', 'Feral instincts'],
    superpowerNames: ['Verdant Touch', 'Blood Howl'],
    initialTraits: { resilience: 0.8, wisdom: 0.7, charisma: 0.25, curiosity: 0.75 },
    initialEmotion: 'anxious',
  },
  {
    name: 'Elix Mordane',
    backstory: 'Alchemist who accidentally made themselves semi-immortal. Now watches everyone age.',
    pros: ['Vast knowledge', 'Patient'],
    cons: ['Detached from mortality', 'Lonely'],
    superpowerNames: ['Spark Forge', 'Echo Memory'],
    initialTraits: { wisdom: 0.95, discipline: 0.8, empathy: 0.4, curiosity: 0.85 },
    initialEmotion: 'melancholy',
  },
  {
    name: 'Nyx Othara',
    backstory: 'Dream-interpreter from a nomadic tribe. Sees the world through symbols and visions.',
    pros: ['Prophetic intuition', 'Calming presence'],
    cons: ['Disoriented in "waking" reality'],
    superpowerNames: ['Dream Weave', 'Chrono Glimpse'],
    initialTraits: { wisdom: 0.85, empathy: 0.8, creativity: 0.75, discipline: 0.4 },
    initialEmotion: 'calm',
  },
  {
    name: 'Jasper Flint',
    backstory: 'Con artist with a heart of gold. Swindles the cruel, gives to the poor.',
    pros: ['Quick thinker', 'Silver tongue'],
    cons: ['Compulsive liar', 'Trust issues'],
    superpowerNames: ['Ember Voice', 'Shadow Step'],
    initialTraits: { cunning: 0.9, charisma: 0.85, discipline: 0.3, empathy: 0.55 },
    initialEmotion: 'excited',
  },
  {
    name: 'Kova Ashenmere',
    backstory: "Daughter of a disgraced noble house. Rebuilding her family's honor brick by brick.",
    pros: ['Iron determination', 'Strategic mind'],
    cons: ['Prideful', 'Difficulty asking for help'],
    superpowerNames: ['Titan Skin', 'Spark Forge'],
    initialTraits: { discipline: 0.85, cunning: 0.8, empathy: 0.35, courage: 0.75 },
    initialEmotion: 'determined',
  },
  {
    name: 'Rune Driftborn',
    backstory: 'Amnesiac who washed ashore with glowing symbols on their skin. Seeking identity.',
    pros: ['Mysterious latent power', 'Open-minded'],
    cons: ['No past', 'Vulnerable to manipulation'],
    superpowerNames: ['Genesis Spark', 'Mind Link'],
    initialTraits: { curiosity: 0.85, resilience: 0.6, cunning: 0.5, wisdom: 0.6 },
    initialEmotion: 'anxious',
  },
  {
    name: 'Pyra Volkheart',
    backstory: 'Fire dancer from the southern wastes. Channels rage into art.',
    pros: ['Passionate', 'Courageous'],
    cons: ['Volatile temper', 'Burns bridges'],
    superpowerNames: ['Rift Walk', 'Blood Howl'],
    initialTraits: { courage: 0.9, creativity: 0.85, aggression: 0.8, discipline: 0.3 },
    initialEmotion: 'excited',
  },
  {
    name: 'Silas Greymoor',
    backstory: "Retired spymaster who knows everyone's secrets. Plays chess with people's lives.",
    pros: ['Master manipulator', 'Vast network'],
    cons: ['Paranoid', 'Morally grey'],
    superpowerNames: ['Pulse Sight', 'Dream Weave'],
    initialTraits: { cunning: 0.95, wisdom: 0.8, empathy: 0.3, charisma: 0.7 },
    initialEmotion: 'calm',
  },
  {
    name: 'Orin Halfmoon',
    backstory: 'Half-awake philosopher who speaks in riddles. Either a genius or mad.',
    pros: ['Profound wisdom', 'Unshakeable calm'],
    cons: ['Useless in emergencies', 'Cryptic'],
    superpowerNames: ['Echo Memory', 'Null Field'],
    initialTraits: { wisdom: 0.95, resilience: 0.85, discipline: 0.5, creativity: 0.7 },
    initialEmotion: 'calm',
  },
  {
    name: 'Fenra Bloodthorn',
    backstory: 'Beast-tamer who bonded too deeply with a predator. Now part wild herself.',
    pros: ['Ferocious protector', 'Keen senses'],
    cons: ['Territorial', 'Distrusts civilization'],
    superpowerNames: ['Blood Howl', 'Shadow Step'],
    initialTraits: { courage: 0.85, aggression: 0.75, empathy: 0.4, resilience: 0.8 },
    initialEmotion: 'anxious',
  },
  {
    name: 'Asha Dewvane',
    backstory: 'Healer who gave up her own health to save a village. Now frail but beloved.',
    pros: ['Selfless', 'Universally trusted'],
    cons: ['Physically weak', 'Martyr complex'],
    superpowerNames: ['Verdant Touch', 'Pulse Sight'],
    initialTraits: { empathy: 0.95, charisma: 0.8, resilience: 0.35, wisdom: 0.75 },
    initialEmotion: 'calm',
  },
  {
    name: 'Zephyr Cain',
    backstory: 'Inventor and tinkerer. Builds impossible machines from scrap. Always has grease on their face.',
    pros: ['Mechanical genius', 'Endlessly optimistic'],
    cons: ['Easily distracted', 'Creates chaos'],
    superpowerNames: ['Spark Forge', 'Rift Walk'],
    initialTraits: { creativity: 0.95, curiosity: 0.9, discipline: 0.25, charisma: 0.6 },
    initialEmotion: 'excited',
  },
  {
    name: 'Vesper Nighthollow',
    backstory: 'Former cult leader who saw the light. Now atones but old followers still seek them.',
    pros: ['Charismatic', 'Deep understanding of darkness'],
    cons: ['Haunted past', 'Feared by some'],
    superpowerNames: ['Dream Weave', 'Ember Voice'],
    initialTraits: { charisma: 0.9, wisdom: 0.8, empathy: 0.65, aggression: 0.35 },
    initialEmotion: 'melancholy',
  },
  {
    name: 'Calder Stonewright',
    backstory: 'Architect who builds structures that seem alive. His buildings hum with energy.',
    pros: ['Visionary creator', 'Grounding presence'],
    cons: ['Perfectionist', 'Neglects relationships'],
    superpowerNames: ['Spark Forge', 'Chrono Glimpse'],
    initialTraits: { creativity: 0.9, discipline: 0.85, empathy: 0.4, wisdom: 0.75 },
    initialEmotion: 'determined',
  },
];
