import { useState } from 'react';
import { Zap, Download, FileText, Code, BarChart2, Table, Layout, type LucideIcon } from 'lucide-react';
import ProgressSteps from '../components/shared/ProgressSteps';
import { OrchestrationStep, Artifact, ArtifactType } from '../types';

const outputTypes: { value: ArtifactType; label: string; icon: LucideIcon }[] = [
  { value: 'document', label: 'Document', icon: FileText },
  { value: 'slide_deck', label: 'Slide Deck', icon: Layout },
  { value: 'report', label: 'Report', icon: BarChart2 },
  { value: 'code', label: 'Code', icon: Code },
  { value: 'spreadsheet', label: 'Spreadsheet', icon: Table },
];

const INITIAL_STEPS: OrchestrationStep[] = [
  { name: 'Intent Parse', status: 'pending' },
  { name: 'Requirements Inference', status: 'pending' },
  { name: 'Task Decomposition', status: 'pending' },
  { name: 'Artifact Plan Generation', status: 'pending' },
  { name: 'Specialist Agent Execution', status: 'pending' },
  { name: 'Quality Assurance', status: 'pending' },
  { name: 'File Export', status: 'pending' },
  { name: 'Workspace Save', status: 'pending' },
];

export default function CreatePage() {
  const [prompt, setPrompt] = useState('');
  const [outputType, setOutputType] = useState<ArtifactType>('document');
  const [isGenerating, setIsGenerating] = useState(false);
  const [steps, setSteps] = useState<OrchestrationStep[]>(INITIAL_STEPS);
  const [artifact, setArtifact] = useState<Artifact | null>(null);

  const simulateGeneration = async () => {
    if (!prompt.trim()) return;
    setIsGenerating(true);
    setArtifact(null);
    const newSteps = INITIAL_STEPS.map(s => ({ ...s, status: 'pending' as const }));
    setSteps(newSteps);

    for (let i = 0; i < newSteps.length; i++) {
      setSteps(prev => prev.map((s, idx) => idx === i ? { ...s, status: 'running' } : s));
      await new Promise(r => setTimeout(r, 600 + Math.random() * 800));
      setSteps(prev => prev.map((s, idx) => idx === i ? { ...s, status: 'complete' } : s));
    }

    const mockArtifact: Artifact = {
      id: 'art-' + Date.now(),
      workspace_id: 'ws-default',
      name: `Generated ${outputType.replace('_', ' ')} — ${new Date().toLocaleDateString()}`,
      type: outputType,
      content: outputType === 'code'
        ? `// Generated by AetherForge\n// Prompt: ${prompt}\n\nfunction main() {\n  console.log("Hello from AetherForge!");\n  // Implementation based on: ${prompt}\n}\n\nmain();`
        : `# ${prompt}\n\nThis document was generated by AetherForge based on your intent.\n\n## Overview\n\nAetherForge analyzed your request and produced the following output tailored to your specifications. The content has been structured according to best practices for ${outputType} generation.\n\n## Key Points\n\n- Comprehensive coverage of the requested topic\n- Structured for clarity and readability\n- Generated with specialist AI agents\n\n## Content\n\nBased on the prompt "${prompt}", the following analysis and content has been generated...\n\n## Conclusion\n\nThis ${outputType} represents the synthesized output from multiple specialist agents working in coordination through the AetherForge orchestration pipeline.`,
      version: 1,
      metadata: {},
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    };
    setArtifact(mockArtifact);
    setIsGenerating(false);
  };

  return (
    <div className="p-8 max-w-5xl">
      <div className="mb-8">
        <h1 className="text-3xl font-bold text-white mb-2">Create</h1>
        <p className="text-[#94a3b8]">Describe your intent and AetherForge will orchestrate the output.</p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Left: Input */}
        <div className="lg:col-span-2 space-y-4">
          <div className="bg-[#1a1a2e] border border-[#2d2d4e] rounded-xl p-5">
            <label className="block text-sm font-medium text-[#94a3b8] mb-2">Describe what you want to create</label>
            <textarea
              value={prompt}
              onChange={e => setPrompt(e.target.value)}
              placeholder="E.g. Write a comprehensive Q3 marketing strategy document for a SaaS company focusing on enterprise customers..."
              className="w-full bg-[#0f0f1a] border border-[#2d2d4e] rounded-lg p-4 text-[#e2e8f0] placeholder-[#475569] resize-none focus:outline-none focus:border-indigo-500 transition-colors text-sm leading-relaxed"
              rows={6}
            />

            <div className="mt-4">
              <label className="block text-sm font-medium text-[#94a3b8] mb-2">Output Type</label>
              <div className="grid grid-cols-5 gap-2">
                {outputTypes.map(({ value, label, icon: Icon }) => (
                  <button
                    key={value}
                    onClick={() => setOutputType(value)}
                    className={`flex flex-col items-center gap-1.5 p-3 rounded-lg border text-xs font-medium transition-all ${
                      outputType === value
                        ? 'bg-indigo-600/20 border-indigo-500 text-indigo-300'
                        : 'border-[#2d2d4e] text-[#94a3b8] hover:border-[#4d4d6e] hover:text-white'
                    }`}
                  >
                    <Icon size={16} />
                    {label}
                  </button>
                ))}
              </div>
            </div>

            <div className="mt-4 flex justify-end">
              <button
                onClick={simulateGeneration}
                disabled={!prompt.trim() || isGenerating}
                className="flex items-center gap-2 px-6 py-3 bg-gradient-to-r from-indigo-600 to-purple-600 hover:from-indigo-500 hover:to-purple-500 text-white font-medium rounded-lg transition-all disabled:opacity-50 disabled:cursor-not-allowed"
              >
                <Zap size={16} />
                {isGenerating ? 'Generating...' : 'Generate'}
              </button>
            </div>
          </div>

          {/* Result */}
          {artifact && (
            <div className="bg-[#1a1a2e] border border-[#2d2d4e] rounded-xl overflow-hidden">
              <div className="flex items-center justify-between p-4 border-b border-[#2d2d4e]">
                <h3 className="text-white font-medium">{artifact.name}</h3>
                <button className="flex items-center gap-2 px-3 py-1.5 bg-indigo-600/20 border border-indigo-500/30 text-indigo-400 rounded-lg text-xs hover:bg-indigo-600/30 transition-colors">
                  <Download size={14} />
                  Download
                </button>
              </div>
              <div className="p-4">
                {artifact.type === 'code' ? (
                  <pre className="bg-[#0f0f1a] rounded-lg p-4 text-sm text-[#e2e8f0] font-mono overflow-auto max-h-64 border border-[#2d2d4e]">
                    {artifact.content}
                  </pre>
                ) : (
                  <div className="bg-[#0f0f1a] rounded-lg p-4 text-sm text-[#94a3b8] whitespace-pre-wrap leading-relaxed max-h-64 overflow-auto border border-[#2d2d4e]">
                    {artifact.content}
                  </div>
                )}
              </div>
            </div>
          )}
        </div>

        {/* Right: Progress */}
        <div className="space-y-4">
          <div className="bg-[#1a1a2e] border border-[#2d2d4e] rounded-xl p-4">
            <h3 className="text-white font-medium mb-3 text-sm">Orchestration Pipeline</h3>
            <ProgressSteps steps={steps} />
          </div>
        </div>
      </div>
    </div>
  );
}
